name: Data Scraper

on:
  schedule:
    - cron: "*/10 * * * *" # every 10th minute
  push:
    branches: ["main"]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Install python packages
        run: pip install -r backend/requirements.txt

      - name: Execute python script
        env:
          GOOGLE_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_TOKEN }}
        run: |
          python backend/scraper.py
          echo "Finished script execution at $(date)"

      - name: Log cron job
        run: echo "Scraping job completed at $(date)"
